#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# build.sh — Local cross-compile for TimerMod (Client Release)
# Requires: clang++ (with MinGW-w64 target support), mingw-w64 headers
#
# Usage:
#   bash build.sh
#
# To install on Ubuntu/Debian:
#   sudo apt-get install -y clang mingw-w64
#
# To populate the SDK submodule (first time only):
#   git submodule update --init --recursive
# ---------------------------------------------------------------------------
set -e

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO_ROOT"

CXX="clang++"
TARGET="x86_64-w64-mingw32"
SDK_CLIENT="StarRupture SDK/Client"
SDK_SRC="StarRupture SDK/Client/SDK"
OUT_DIR="bin/x64/Client Release/plugins"
OUT_DLL="$OUT_DIR/TimerMod.dll"

# ---------------------------------------------------------------------------
# 1. Check clang
# ---------------------------------------------------------------------------
if ! command -v "$CXX" &>/dev/null; then
    echo ""
    echo "ERROR: $CXX not found."
    echo "Install with:  sudo apt-get install -y clang"
    exit 1
fi

# ---------------------------------------------------------------------------
# 2. Check SDK submodule
# ---------------------------------------------------------------------------
if [ ! -f "$SDK_SRC/Basic.cpp" ]; then
    echo ""
    echo "ERROR: StarRupture SDK submodule is empty."
    echo "Run:  git submodule update --init --recursive"
    exit 1
fi

# ---------------------------------------------------------------------------
# 3. Generate empty assertion stubs
#    Assertions.inl was generated by Dumper-7 with MSVC-computed offsets.
#    All DUMPER7_ASSERTS_* macros expand to ';' (valid empty declaration at
#    C++ namespace scope) so the static_assert offset checks are skipped.
#    The x64 Windows ABI is matched correctly at runtime regardless.
# ---------------------------------------------------------------------------
echo "Generating AssertionNoops.h..."
grep -Eo '^#define DUMPER7_ASSERTS_[A-Za-z0-9_]+' \
    "$SDK_CLIENT/Assertions.inl" > "include/AssertionNoops.h"

# ---------------------------------------------------------------------------
# 4. Generate Windows.h case-sensitivity shim
#    MinGW ships windows.h (all lowercase); the Dumper-7 SDK headers use the
#    canonical capitalisation Windows.h.  On a case-sensitive Linux filesystem
#    those are different names, so we provide a shim that redirects.
#    This file is NOT committed and is not used in MSVC builds.
# ---------------------------------------------------------------------------
echo "Generating Windows.h shim..."
printf '// Auto-generated by build.sh — DO NOT COMMIT\n// Redirects <Windows.h> to MinGW'\''s <windows.h> on case-sensitive filesystems.\n#pragma once\n#include <windows.h>\n' \
    > "include/Windows.h"

# ---------------------------------------------------------------------------
# 5. Build
# ---------------------------------------------------------------------------
mkdir -p "$OUT_DIR"

echo "Building TimerMod (Client Release)..."

"$CXX" \
    --target="$TARGET" \
    -std=c++20 \
    -fms-extensions \
    -fms-compatibility-version=19.29 \
    -fno-char8_t \
    -include sdk_compat.h \
    -Wno-invalid-constexpr \
    -Wno-c++11-narrowing \
    -shared \
    -O2 \
    -DMODLOADER_CLIENT_BUILD \
    -DNDEBUG \
    -DTIMERMOD_EXPORTS \
    -D_WINDOWS \
    -D_USRDLL \
    -D_WIN32_WINNT=0x0601 \
    -I "TimerMod" \
    -I "include" \
    -I "$SDK_CLIENT" \
    -I "$SDK_SRC" \
    "$SDK_SRC/Basic.cpp" \
    "$SDK_SRC/CoreUObject_functions.cpp" \
    "$SDK_SRC/Engine_functions.cpp" \
    "$SDK_SRC/Chimera_functions.cpp" \
    "TimerMod/dllmain.cpp" \
    "TimerMod/plugin.cpp" \
    "TimerMod/plugin_config.cpp" \
    "TimerMod/timer_tracker.cpp" \
    "TimerMod/obelisk_tracker.cpp" \
    "TimerMod/data_export.cpp" \
    "TimerMod/hud_overlay.cpp" \
    -static-libgcc \
    -static-libstdc++ \
    -o "$OUT_DLL" \
    -lkernel32 -luser32

echo ""
echo "OK: $OUT_DLL"
