name: Build TimerMod

on:
  push:
    branches:
      - 'dev/*'
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Build Client Release
        run: |
          msbuild "StarRupture-TimerMod.sln" `
            /p:Configuration="Client Release" `
            /p:Platform=x64 `
            /m `
            /v:minimal

      - name: Upload Client DLL
        uses: actions/upload-artifact@v7
        with:
          name: TimerMod-Client
          path: bin/x64/Client Release/plugins/TimerMod.dll
